### ISSUE TITLE
Wrong timestamp

### ISSUE THREAD

**Issue by vankk** [MeitarR/DiscordHooks#1]
Hello, I'm having an issue with the timestamp, the message is been displayed with the time delayed by 2 hours. Check the image below.

![image](https://user-images.githubusercontent.com/14372849/52124787-8f2e8180-2611-11e9-8034-1a9151fe62c6.png)

I'm using `datetime.now()` when I simply run:
```python
from datetime import datetime

print(datetime.now())
```

It displayed the correct time: `2019-02-01 11:08:18.332363`. What that can may be this difference between thoses two times?

Thanks.

Regards,
vankk.

**Comment by MeitarR** [comment]
You should use utcnow instead of now

**Comment by vankk** [comment]
Ooh, thanks. It worked! Do you mind in explain this difference between utcnow & now?

**Comment by MeitarR** [comment]
Of course.
now returns Datetime object that represents the current time at your timezone.
utcnow returns Datetime object that represents the current time at utc+0.

Discord is expecting to get the utc time and them the client is rendering the time according to the client's timezone

**Comment by vankk** [comment]
Oh, didn't know about that. Thank for you explaning!
